### ISSUE TITLE
Menu Bar Data Handling 

### ISSUE THREAD

**Issue by DilanGoodwin** [DilanGoodwin/FinalYearModuleSelectionTool#9]
With the design changes made to the menu bar area there are some behind the scenes code items that will need to be changed to allow the update to work correctly.

## Saved Courses
The file in which courses are loaded from will need to be edited to allow for courses to be added/removed from the file from within the program. Currently the external dat file contains an array of courses that only allows for 2 courses to be saved at a single time, this will need to be changed to allow for an possible infinite number of courses to be saved to the file.

Validation for saved courses will also need to take place and will influence what courses the user is able to select that they are on. This is due to the limitation of module credits being a factor on whether a user can move onto another section within the program. An example would be creating a course that has not modules, the user should not be able to select this as a course that they can take as there are no modules that they can select within the other sections.
In total a course should contain enough moudles to reach 120 credits per term, including year long modules. This number is derived from the fact that uses have to select modules they would like to take and modules that they would like to reserve, if they are unable to reach this number then they will never be able to exit the application with a text file stating their information and the modules they would like to take.

Courses should be able to be created and saved with no modules attached to them at all but they should not be displayed to the user in the profile creation pane. 

## Saved Modules
Modules should be able to be created but have no course attached to them, however all other areas of the module should be filled in before the module can be created. 

If a module has not course assigned to it then it should be saved before the application is closed, this requires a rework of the current saving mechanism for courses and modules. Modules with no course assigned to them should not be selectable to the user outside of the settings pane. 

## TODO
- [ ] Update Courses that are already saved to a file
- [ ] Change the courses that are passed to the profile creation pane to not include courses that do not reach a given number of credits per term
- [ ] Implement event handlers for add, edit, remove buttons within modules setting area
- [ ] Implement event handlers for add, edit, remove buttons within courses setting area
- [ ] Re-work saving mechanism for courses and moudles to be imported into the program
